---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cert-manager/cluster-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
